// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.NET_MVC_2022_12D_PP_Encuestadora.Context;

namespace WebApp.NET_MVC_2022_12D_PP_Encuestadora.Migrations
{
    [DbContext(typeof(EncuestadoraDBContext))]
    [Migration("20220607023308_CrearBaseDeDatos_v3")]
    partial class CrearBaseDeDatos_v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cuitCliente")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("domicilioCliente")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("empresaCliente")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("mailCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("passwordCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("precioCliente")
                        .HasColumnType("int");

                    b.HasKey("ClienteId");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Encuesta", b =>
                {
                    b.Property<int>("EncuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("datetimeCreacionEncuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("datetimeVencimientoEncuesta")
                        .HasColumnType("datetime2");

                    b.Property<int>("puntosEncuesta")
                        .HasColumnType("int");

                    b.Property<string>("tituloEncuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("EncuestaId");

                    b.HasIndex("ClienteId");

                    b.ToTable("encuestas");
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.EncuestasUsuarios", b =>
                {
                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("EncuestaId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("encuestasUsuarios");
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.OpcionPregunta", b =>
                {
                    b.Property<int>("OpcionPreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PreguntaId")
                        .HasColumnType("int");

                    b.Property<bool>("opcionSeleccionada")
                        .HasColumnType("bit");

                    b.Property<string>("tituloOpcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("OpcionPreguntaId");

                    b.HasIndex("PreguntaId");

                    b.ToTable("opciones");
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Pregunta", b =>
                {
                    b.Property<int>("PreguntaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EncuestaId")
                        .HasColumnType("int");

                    b.Property<int>("tipoPregunta")
                        .HasColumnType("int");

                    b.Property<string>("tituloPregunta")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("PreguntaId");

                    b.HasIndex("EncuestaId");

                    b.ToTable("preguntas");
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("datetimeFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("dniUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(8)")
                        .HasMaxLength(8);

                    b.Property<string>("domicilioUsuario")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("mailUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("nombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(80)")
                        .HasMaxLength(80);

                    b.Property<string>("passwordUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("preferenciaUsuario")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Encuesta", b =>
                {
                    b.HasOne("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Cliente", "Cliente")
                        .WithMany("encuestas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.EncuestasUsuarios", b =>
                {
                    b.HasOne("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Encuesta", "Encuesta")
                        .WithMany("EncuestasUsuarios")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Usuario", "Usuario")
                        .WithMany("EncuestasUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.OpcionPregunta", b =>
                {
                    b.HasOne("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Pregunta", "Pregunta")
                        .WithMany("opciones")
                        .HasForeignKey("PreguntaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Pregunta", b =>
                {
                    b.HasOne("WebApp.NET_MVC_2022_12D_PP_Encuestadora.Models.Encuesta", "Encuesta")
                        .WithMany("preguntas")
                        .HasForeignKey("EncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
